name: 2203DESIGN
favicon: null
layout_spectrum: 0.24164
typography_spectrum: 0.13213
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2ba425'
    - '#ffffff'
    - '#b8e1b6'
    - '#8bcd87'
    - '#53b54e'
  brandStrength: 0.9860947683919221
  lightness: 0.27811817335896194
  saturation: 0.5349061605520546
  rhythmicContrast: 0.2667330021504313
purpose: []
